<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  

  
  <title>Kotlin协程异常处理 | Aichi_B7A</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="Kotlin的协程满足结构化语义：  A parent-Coroutine finishes only after all its child-Coroutines have finished.  When a parent-Coroutine or scope finishes abnormally, either through cancelation or through an except">
<meta property="og:type" content="article">
<meta property="og:title" content="Kotlin协程异常处理">
<meta property="og:url" content="https://tedaliez.github.io/2020/09/12/Kotlin%E5%8D%8F%E7%A8%8B%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86/index.html">
<meta property="og:site_name" content="Aichi_B7A">
<meta property="og:description" content="Kotlin的协程满足结构化语义：  A parent-Coroutine finishes only after all its child-Coroutines have finished.  When a parent-Coroutine or scope finishes abnormally, either through cancelation or through an except">
<meta property="og:locale">
<meta property="article:published_time" content="2020-09-12T01:09:48.000Z">
<meta property="article:modified_time" content="2020-10-31T04:38:53.895Z">
<meta property="article:author" content="Jian Guo">
<meta property="article:tag" content="kotlin, 协程">
<meta name="twitter:card" content="summary">
  
    <link rel="alternate" href="/atom.xml" title="Aichi_B7A" type="application/atom+xml">
  
  
    <link rel="icon" href="/favicon.png">
  
  
    <link href="//fonts.googleapis.com/css?family=Source+Code+Pro" rel="stylesheet" type="text/css">
  
  
<link rel="stylesheet" href="/css/style.css">

<meta name="generator" content="Hexo 5.2.0"></head>

<body>
  <div id="container">
    <div id="wrap">
      <header id="header">
  <div id="banner"></div>
  <div id="header-outer" class="outer">
    <div id="header-title" class="inner">
      <h1 id="logo-wrap">
        <a href="/" id="logo">Aichi_B7A</a>
      </h1>
      
    </div>
    <div id="header-inner" class="inner">
      <nav id="main-nav">
        <a id="main-nav-toggle" class="nav-icon"></a>
        
          <a class="main-nav-link" href="/">Home</a>
        
          <a class="main-nav-link" href="/archives">Archives</a>
        
      </nav>
      <nav id="sub-nav">
        
          <a id="nav-rss-link" class="nav-icon" href="/atom.xml" title="RSS Feed"></a>
        
        <a id="nav-search-btn" class="nav-icon" title="Search"></a>
      </nav>
      <div id="search-form-wrap">
        <form action="//google.com/search" method="get" accept-charset="UTF-8" class="search-form"><input type="search" name="q" class="search-form-input" placeholder="Search"><button type="submit" class="search-form-submit">&#xF002;</button><input type="hidden" name="sitesearch" value="https://tedaliez.github.io"></form>
      </div>
    </div>
  </div>
</header>
      <div class="outer">
        <section id="main"><article id="post-Kotlin协程异常处理" class="article article-type-post" itemscope itemprop="blogPost">
  <div class="article-meta">
    <a href="/2020/09/12/Kotlin%E5%8D%8F%E7%A8%8B%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86/" class="article-date">
  <time datetime="2020-09-12T01:09:48.000Z" itemprop="datePublished">2020-09-12</time>
</a>
    
  </div>
  <div class="article-inner">
    
    
      <header class="article-header">
        
  
    <h1 class="article-title" itemprop="name">
      Kotlin协程异常处理
    </h1>
  

      </header>
    
    <div class="article-entry" itemprop="articleBody">
      
        <p>Kotlin的协程满足结构化语义：</p>
<ol>
<li><p>A parent-Coroutine finishes only after all its child-Coroutines have finished.</p>
</li>
<li><p>When a parent-Coroutine or scope finishes abnormally, either through cancelation or through an exception, all its child-Coroutines, that are still active, are canceled and new child-Coroutines can no longer be launched.</p>
</li>
<li><p>When a child-Coroutine finishes abnormally, its parent-Coroutine or scope finishes abnormally.</p>
</li>
</ol>
<p>针对第三点，无论是<code>CoroutineScope.async</code>或<code>CoroutineScope.launch</code>，以异常结束，只要是在一个scope中，他的父协程也会以异常结束。<code>async</code>和<code>launch</code>唯一不同的地方在于<code>async</code>需要调用await才会执行协程内容。即使我们对子协程进行了try-catch处理异常，父协程仍旧会拿着这个异常作为结果结束</p>
<h2 id="async的异常处理"><a href="#async的异常处理" class="headerlink" title="async的异常处理"></a>async的异常处理</h2><pre><code>不管是哪个启动器(launch, async等)，在应用了作用域之后，都会按照**作用域的语义**进行异常扩散，进而触发相应的取消操作，对于 async 来说就算不调用 await 来获取这个异常，它也会在 coroutineScope 当中触发父协程的取消逻辑，这一点请大家注意。
</code></pre><p>以CoroutineScope(Dispatchers.Main)作为根作用域为例，下面展示几个case</p>
<figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">CoroutineScope(Dispatchers.Main).launch &#123;</span><br><span class="line">    <span class="keyword">val</span> foo = async &#123;</span><br><span class="line">        <span class="keyword">throw</span> IllegalStateException(<span class="string">&quot;test&quot;</span>)</span><br><span class="line">    &#125;</span><br><span class="line">    Log.d(<span class="string">&quot;Foo&quot;</span>, <span class="string">&quot;test&quot;</span>)</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>上面的代码即使没有调用<code>foo.await()</code>, 也会扩散到<code>Thread.UncaughtExceptionHandler</code>中。这段代码的执行结果是</p>
<pre><code>D/Foo: [, , 0]:test
</code></pre><p>同时app crash</p>
<p>这里我们应该这么理解，虽然是对<code>await()</code>进行了try-catch，但这里是对执行结果的<code>try-catch</code>, 这不影响协程自己的异常传递规则，在async中的协程scope抛出异常后，此时异常是未捕获状态；因此会向父协程scope<code>coroutineScope</code>转播, <code>coroutineScope</code>继续向<code>viewModelScope</code>传播，最终来到UncaughtExceptionHandler处处理</p>
<p>那么考虑一下直接加入<code>try-catch</code>:</p>
<figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line">CoroutineScope(Dispatchers.Main).launch &#123;</span><br><span class="line">    <span class="keyword">val</span> foo = async &#123;</span><br><span class="line">        <span class="keyword">throw</span> IllegalStateException(<span class="string">&quot;test&quot;</span>)</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">        foo.await()</span><br><span class="line">    &#125; <span class="keyword">catch</span> (e : IllegalStateException) &#123;</span><br><span class="line">        Log.e(<span class="string">&quot;Foo&quot;</span>, <span class="string">&quot;CoroutineScope caught exception: <span class="variable">$e</span>&quot;</span>)</span><br><span class="line">    &#125;</span><br><span class="line">    Log.d(<span class="string">&quot;Foo&quot;</span>, <span class="string">&quot;test&quot;</span>)</span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p>输出结果为:</p>
<pre><code>E/Foo: [, , 0]:CoroutineScope caught exception: java.lang.IllegalStateException: test
D/Foo: [, , 0]:test
</code></pre><p>同时app crash</p>
<p>这里虽然我们对await进行了try-catch，打印了异常信息，但是根据作用域规则，这里我们的异常行为发生了扩散，从子协程扩散到根协程，最终扩散到<code>Thread.UncaughtExceptionHandler</code>中，对于安卓系统而言，就是引发了crash</p>
<p>那么如果我们在扩散的scope外层进行try-catch能否解决问题呢？尝试如下的代码:</p>
<figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line">CoroutineScope(Dispatchers.Main).launch &#123;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">        coroutineScope &#123;</span><br><span class="line">            <span class="keyword">val</span> foo = async &#123;</span><br><span class="line">                <span class="keyword">throw</span> IllegalStateException(<span class="string">&quot;test&quot;</span>)</span><br><span class="line">            &#125;</span><br><span class="line">            Log.d(<span class="string">&quot;Foo&quot;</span>, <span class="string">&quot;test&quot;</span>)</span><br><span class="line">        &#125;</span><br><span class="line">    &#125; <span class="keyword">catch</span> (e: IllegalStateException) &#123;</span><br><span class="line">        Log.e(<span class="string">&quot;Foo&quot;</span>, <span class="string">&quot;catch expection from outerScope: <span class="variable">$e</span>&quot;</span>)</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p>输出结果为:</p>
<pre><code>E/Foo: [, , 0]:CoroutineScope caught exception: java.lang.IllegalStateException: test
D/Foo: [, , 0]:test
</code></pre><p>此时app 不再crash</p>
<p>如果我们在添加await()同时进行try-catch:</p>
<figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line">CoroutineScope(Dispatchers.Main).launch &#123;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">        coroutineScope &#123;</span><br><span class="line">            <span class="keyword">val</span> foo = async &#123;</span><br><span class="line">                <span class="keyword">throw</span> IllegalStateException(<span class="string">&quot;test&quot;</span>)</span><br><span class="line">            &#125;</span><br><span class="line">            <span class="keyword">try</span> &#123;</span><br><span class="line">                foo.await()</span><br><span class="line">            &#125; <span class="keyword">catch</span> (e: IllegalStateException) &#123;</span><br><span class="line">                Log.e(<span class="string">&quot;Foo&quot;</span>, <span class="string">&quot;catch expection from innerScope: <span class="variable">$e</span>&quot;</span>)</span><br><span class="line">            &#125;</span><br><span class="line">            Log.d(<span class="string">&quot;Foo&quot;</span>, <span class="string">&quot;test&quot;</span>)</span><br><span class="line">        &#125;</span><br><span class="line">    &#125; <span class="keyword">catch</span> (e: IllegalStateException) &#123;</span><br><span class="line">        Log.e(<span class="string">&quot;Foo&quot;</span>, <span class="string">&quot;catch expection from outerScope: <span class="variable">$e</span>&quot;</span>)</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p>输出结果为:</p>
<pre><code>E/Foo: [, , 0]:catch expection from innerScope: java.lang.IllegalStateException: test
D/Foo: [, , 0]:test
E/Foo: [, , 0]:catch expection from outerScope: java.lang.IllegalStateException: test
</code></pre><p>此时app 也不再crash，但我们会发现我们的两处<code>try-catch</code>均被触发</p>
<p>这也说明<strong>在协程中，异常的扩散并不遵循try-catch语法构成的作用域</strong></p>
<p>另一种方式就是换用一个不进行扩散语义的协程作用域，即使用supervisorScope</p>
<figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line">CoroutineScope(Dispatchers.Main).launch &#123;</span><br><span class="line">    supervisorScope &#123;</span><br><span class="line">        <span class="keyword">val</span> foo = async &#123;</span><br><span class="line">            <span class="keyword">throw</span> IllegalStateException(<span class="string">&quot;test&quot;</span>)</span><br><span class="line">        &#125;</span><br><span class="line">        Log.d(<span class="string">&quot;Foo&quot;</span>, <span class="string">&quot;test&quot;</span>)</span><br><span class="line">    &#125;</span><br><span class="line">    </span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p>这段代码的输出结果为</p>
<pre><code>D/Foo: [, , 0]:test
</code></pre><p>app 不发生crash, 同时没有IllegalStateException(“test”)的日志打印</p>
<p>这里的核心在于，我们的async是在<code>supervisorScope</code>作用域下，根据文档描述，这个作用域下的协程出现取消情况（异常抛出时）不会向外扩散</p>
<p>假如加上try-catch</p>
<figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line">CoroutineScope(Dispatchers.Main).launch &#123;</span><br><span class="line">    supervisorScope &#123;</span><br><span class="line">        <span class="keyword">val</span> foo = async &#123;</span><br><span class="line">            <span class="keyword">throw</span> IllegalStateException(<span class="string">&quot;test&quot;</span>)</span><br><span class="line">        &#125;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            foo.await()</span><br><span class="line">        &#125; <span class="keyword">catch</span> (e: IllegalStateException) &#123;</span><br><span class="line">            Log.e(<span class="string">&quot;Foo&quot;</span>, <span class="string">&quot;CoroutineScope caught exception: <span class="variable">$e</span>&quot;</span>)</span><br><span class="line">        &#125;</span><br><span class="line">        Log.d(<span class="string">&quot;Foo&quot;</span>, <span class="string">&quot;test&quot;</span>)</span><br><span class="line">    &#125;</span><br><span class="line">    </span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p>我们得到结果</p>
<pre><code>E/Foo: [, , 0]:CoroutineScope caught exception: java.lang.IllegalStateException: test
D/Foo: [, , 0]:test
</code></pre><p>app 不发生crash</p>
<p>同理，我们的async是在<code>supervisorScope</code>作用域下，根据文档描述，这个作用域下的协程出现取消情况（异常抛出时）不会向外扩散，因此不会向外扩散到<code>Thread.UncaughtExceptionHandler</code>。同时，try-catch对await()发生作用，我们打印出了异常的信息</p>
<h2 id="withContext的异常处理"><a href="#withContext的异常处理" class="headerlink" title="withContext的异常处理"></a>withContext的异常处理</h2><p>那么对比一下withContext的处理我们就会发现不同</p>
<figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line">viewModelScope.launch &#123;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">        withContext(Dispatchers.Default) &#123;</span><br><span class="line">            <span class="keyword">throw</span> IllegalArgumentException(<span class="string">&quot;Test&quot;</span>)</span><br><span class="line">        &#125;</span><br><span class="line">    &#125; <span class="keyword">catch</span> (e: Exception) &#123;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p>这里<code>withContext</code>直接就是一个协程scope，我们的try-catch直接作用于整个withContext构造的scope，因此异常被捕获的同时，不再向<code>viewModelScope</code>传播</p>
<h2 id="supervisorScope"><a href="#supervisorScope" class="headerlink" title="supervisorScope"></a>supervisorScope</h2><p>如何能够让子协程抛出异常的情况下，父协程不会终止所以其子协程和自己呢？这就引入了supervisorScope</p>
<figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">val</span> result = supervisorScope &#123;</span><br><span class="line">    ...</span><br><span class="line">    <span class="keyword">val</span> supervisedChild1 = <span class="keyword">this</span>.launch &#123; ... &#125;</span><br><span class="line">    ...</span><br><span class="line">    <span class="keyword">val</span> supervisedChild2 = <span class="keyword">this</span>.async &#123; ... &#125;</span><br><span class="line">    ...</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>此时，若child1或child2任意一个抛出异常，也不会使另一个child和<code>supervising parent</code>停止</p>
<h2 id="小结"><a href="#小结" class="headerlink" title="小结"></a>小结</h2><p>最终我们得到了协程的Structured Concurrency含义:</p>
<ol>
<li><p>A parent-Coroutine finishes only after all its child-Coroutines have finished.</p>
</li>
<li><p>When a parent-Coroutine or scope finishes abnormally, either through cancelation or through an exception, all its child-Coroutines, that are still active, are canceled and new child-Coroutines can no longer be launched.</p>
</li>
<li><p>When a child-Coroutine finishes abnormally, its parent-Coroutine or scope (a) finishes abnormally if the parent is not a supervisor or (b) keeps running if the parent is a supervisor.</p>
</li>
</ol>
<h2 id="P-S-协程中的异常最佳实践"><a href="#P-S-协程中的异常最佳实践" class="headerlink" title="P.S 协程中的异常最佳实践"></a>P.S 协程中的异常最佳实践</h2><p>通过上文中对await，withContext的异常处理的方式，我们会发现在协程中处理异常其实是一件非常麻烦的事情，其异常的扩散规则并不合<code>try-catch</code>的作用域对应。因此这里简单提一下如何在实际项目中处理这种异常</p>
<p>Kotlin中对异常处理有两种推荐方式:</p>
<ol>
<li>default value</li>
<li>Wrapper Seal class</li>
</ol>
<p>第一种方式就是返回一个跟函数签名同类型的默认值，例如</p>
<figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">fun</span> <span class="title">toIntSafely</span><span class="params">(defaultValue: <span class="type">Int</span>)</span></span> : <span class="built_in">Int</span> &#123;</span><br><span class="line">    <span class="keyword">return</span> <span class="keyword">try</span> &#123;</span><br><span class="line">        parseInt(<span class="keyword">this</span>)</span><br><span class="line">    &#125; <span class="keyword">catch</span> (e: NumberFormatException) &#123;</span><br><span class="line">        <span class="keyword">return</span> defaultValue</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p>第二种方式则是在API设计上使用一个Wrapper Class来包装出现的异常，使用这个Wrapper Class来保证Type-Check，举例来说:</p>
<figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"></span><br><span class="line"><span class="keyword">sealed</span> <span class="class"><span class="keyword">class</span> <span class="title">ParsedDate</span> </span>&#123;</span><br><span class="line">    <span class="keyword">data</span> <span class="class"><span class="keyword">class</span> <span class="title">Success</span></span>(<span class="keyword">val</span> date: Date) : ParsedDate()</span><br><span class="line">    <span class="keyword">data</span> <span class="class"><span class="keyword">class</span> <span class="title">Failure</span></span>(<span class="keyword">val</span> errorOffset: <span class="built_in">Int</span>) : ParsedDate()</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">fun</span> DateFormat.<span class="title">tryParse</span><span class="params">(text: <span class="type">String</span>)</span></span>: ParsedDate =</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">        ParsedDate.Success(parse(text))</span><br><span class="line">    &#125; <span class="keyword">catch</span> (e: ParseException) &#123;</span><br><span class="line">        ParsedDate.Failure(e.errorOffset)</span><br><span class="line">    &#125;</span><br></pre></td></tr></table></figure>
<p>那么对调用者而言,<code>tryParse</code>的结果一定是一个<code>ParsedDate</code>对象，而对异常无感知</p>
<p>结合协程使用来说，我们应该直接在一个作用域内，就返回一个default value或Wrapper Seal class，例如</p>
<figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line"></span><br><span class="line"><span class="keyword">sealed</span> <span class="class"><span class="keyword">class</span> <span class="title">ParsedDate</span> </span>&#123;</span><br><span class="line">    <span class="keyword">data</span> <span class="class"><span class="keyword">class</span> <span class="title">Success</span></span>(<span class="keyword">val</span> date: Date) : ParsedDate()</span><br><span class="line">    <span class="keyword">data</span> <span class="class"><span class="keyword">class</span> <span class="title">Failure</span></span>(<span class="keyword">val</span> errorOffset: <span class="built_in">Int</span>) : ParsedDate()</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">CoroutineScope(Dispatchers.Main).launch &#123;</span><br><span class="line">    <span class="keyword">val</span> foo = async &#123;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            <span class="keyword">throw</span> IllegalStateException(<span class="string">&quot;test&quot;</span>)</span><br><span class="line">        &#125; <span class="keyword">catch</span> (e: IllegalStateException) &#123;</span><br><span class="line">            Log.e(<span class="string">&quot;Foo&quot;</span>, <span class="string">&quot;catch exception inside: <span class="variable">$e</span>&quot;</span>)</span><br><span class="line">            ParsedDate.Failure(-<span class="number">1</span>)</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">val</span> rst = foo.await()</span><br><span class="line">    Log.d(<span class="string">&quot;Foo&quot;</span>, <span class="string">&quot;return rst: <span class="subst">$&#123;rst.errorOffset&#125;</span>&quot;</span>)</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>输出结果:</p>
<pre><code>E/Foo: [, , 0]:catch exception inside: java.lang.IllegalStateException: test
D/Foo: [, , 0]:return rst: -1
</code></pre><p>同时app无crash，无异常日志打印</p>
<p>ref: </p>
<p><a target="_blank" rel="noopener" href="https://www.bennyhuo.com/2019/04/23/coroutine-exceptions/#4-%E5%BC%82%E5%B8%B8%E4%BC%A0%E6%92%AD">https://www.bennyhuo.com/2019/04/23/coroutine-exceptions/#4-%E5%BC%82%E5%B8%B8%E4%BC%A0%E6%92%AD</a></p>
<p><a target="_blank" rel="noopener" href="https://johnnyshieh.me/posts/kotlin-coroutine-exception-handling/">https://johnnyshieh.me/posts/kotlin-coroutine-exception-handling/</a></p>
<p><a target="_blank" rel="noopener" href="https://medium.com/@elizarov/structured-concurrency-722d765aa952">https://medium.com/@elizarov/structured-concurrency-722d765aa952</a></p>
<p><a target="_blank" rel="noopener" href="https://medium.com/the-kotlin-chronicle/coroutine-exceptions-supervision-15056802998b">https://medium.com/the-kotlin-chronicle/coroutine-exceptions-supervision-15056802998b</a></p>
<p><a target="_blank" rel="noopener" href="https://medium.com/the-kotlin-chronicle/coroutine-exceptions-3378f51a7d33">https://medium.com/the-kotlin-chronicle/coroutine-exceptions-3378f51a7d33</a></p>
<p><a target="_blank" rel="noopener" href="https://github.com/Kotlin/kotlinx.coroutines/issues/753">https://github.com/Kotlin/kotlinx.coroutines/issues/753</a></p>

      
    </div>
    <footer class="article-footer">
      <a data-url="https://tedaliez.github.io/2020/09/12/Kotlin%E5%8D%8F%E7%A8%8B%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86/" data-id="ckgx4rr7i000mi8x701ovf1ub" class="article-share-link">Share</a>
      
      
  <ul class="article-tag-list" itemprop="keywords"><li class="article-tag-list-item"><a class="article-tag-list-link" href="/tags/kotlin-%E5%8D%8F%E7%A8%8B/" rel="tag">kotlin, 协程</a></li></ul>

    </footer>
  </div>
  
    
<nav id="article-nav">
  
    <a href="/2020/09/13/FFMpeg-Android%E5%BC%80%E5%8F%91-%E7%AE%80%E5%8D%95%E9%9F%B3%E8%A7%86%E9%A2%91%E5%90%8C%E6%AD%A5/" id="article-nav-newer" class="article-nav-link-wrap">
      <strong class="article-nav-caption">Newer</strong>
      <div class="article-nav-title">
        
          FFMpeg-Android开发-简单音视频同步
        
      </div>
    </a>
  
  
    <a href="/2020/08/29/FFMpeg-Android%E5%BC%80%E5%8F%91-%E7%AE%80%E5%8D%95%E6%92%AD%E6%94%BE%E9%9F%B3%E9%A2%91/" id="article-nav-older" class="article-nav-link-wrap">
      <strong class="article-nav-caption">Older</strong>
      <div class="article-nav-title">FFMpeg-Android开发-简单播放音频</div>
    </a>
  
</nav>

  
</article>

</section>
        
          <aside id="sidebar">
  
    

  
    
  <div class="widget-wrap">
    <h3 class="widget-title">Tags</h3>
    <div class="widget">
      <ul class="tag-list" itemprop="keywords"><li class="tag-list-item"><a class="tag-list-link" href="/tags/Android-ROOM/" rel="tag">Android, ROOM</a></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/NDK/" rel="tag">NDK</a></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/TypeScript/" rel="tag">TypeScript</a></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/WebAssembly/" rel="tag">WebAssembly</a></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/WebView-JSBridge/" rel="tag">WebView, JSBridge</a></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/android/" rel="tag">android</a></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/android-jetpack-compose/" rel="tag">android, jetpack compose</a></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/android-mmkv/" rel="tag">android, mmkv</a></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/android-textview/" rel="tag">android, textview</a></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/kotlin/" rel="tag">kotlin</a></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/kotlin-coroutine/" rel="tag">kotlin, coroutine</a></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/kotlin-%E5%8D%8F%E7%A8%8B/" rel="tag">kotlin, 协程</a></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/v8-WebAssembly/" rel="tag">v8, WebAssembly</a></li></ul>
    </div>
  </div>


  
    
  <div class="widget-wrap">
    <h3 class="widget-title">Tag Cloud</h3>
    <div class="widget tagcloud">
      <a href="/tags/Android-ROOM/" style="font-size: 10px;">Android, ROOM</a> <a href="/tags/NDK/" style="font-size: 10px;">NDK</a> <a href="/tags/TypeScript/" style="font-size: 10px;">TypeScript</a> <a href="/tags/WebAssembly/" style="font-size: 15px;">WebAssembly</a> <a href="/tags/WebView-JSBridge/" style="font-size: 10px;">WebView, JSBridge</a> <a href="/tags/android/" style="font-size: 20px;">android</a> <a href="/tags/android-jetpack-compose/" style="font-size: 10px;">android, jetpack compose</a> <a href="/tags/android-mmkv/" style="font-size: 20px;">android, mmkv</a> <a href="/tags/android-textview/" style="font-size: 10px;">android, textview</a> <a href="/tags/kotlin/" style="font-size: 10px;">kotlin</a> <a href="/tags/kotlin-coroutine/" style="font-size: 10px;">kotlin, coroutine</a> <a href="/tags/kotlin-%E5%8D%8F%E7%A8%8B/" style="font-size: 10px;">kotlin, 协程</a> <a href="/tags/v8-WebAssembly/" style="font-size: 10px;">v8, WebAssembly</a>
    </div>
  </div>

  
    
  <div class="widget-wrap">
    <h3 class="widget-title">Archives</h3>
    <div class="widget">
      <ul class="archive-list"><li class="archive-list-item"><a class="archive-list-link" href="/archives/2020/11/">November 2020</a></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2020/09/">September 2020</a></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2020/08/">August 2020</a></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2020/07/">July 2020</a></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2020/05/">May 2020</a></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2020/03/">March 2020</a></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2020/02/">February 2020</a></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2020/01/">January 2020</a></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2019/12/">December 2019</a></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2019/11/">November 2019</a></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2019/09/">September 2019</a></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2019/07/">July 2019</a></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2019/06/">June 2019</a></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2019/05/">May 2019</a></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2019/03/">March 2019</a></li></ul>
    </div>
  </div>


  
    
  <div class="widget-wrap">
    <h3 class="widget-title">Recent Posts</h3>
    <div class="widget">
      <ul>
        
          <li>
            <a href="/2020/11/14/Android%E5%B5%8C%E5%A5%97%E6%BB%9A%E5%8A%A8/">Android嵌套滚动</a>
          </li>
        
          <li>
            <a href="/2020/09/13/FFMpeg-Android%E5%BC%80%E5%8F%91-%E7%AE%80%E5%8D%95%E9%9F%B3%E8%A7%86%E9%A2%91%E5%90%8C%E6%AD%A5/">FFMpeg-Android开发-简单音视频同步</a>
          </li>
        
          <li>
            <a href="/2020/09/12/Kotlin%E5%8D%8F%E7%A8%8B%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86/">Kotlin协程异常处理</a>
          </li>
        
          <li>
            <a href="/2020/08/29/FFMpeg-Android%E5%BC%80%E5%8F%91-%E7%AE%80%E5%8D%95%E6%92%AD%E6%94%BE%E9%9F%B3%E9%A2%91/">FFMpeg-Android开发-简单播放音频</a>
          </li>
        
          <li>
            <a href="/2020/08/23/FFMpeg-Android%E5%BC%80%E5%8F%91-%E7%AE%80%E5%8D%95%E6%92%AD%E6%94%BE%E8%A7%86%E9%A2%91/">FFMpeg-Android开发-简单播放视频</a>
          </li>
        
      </ul>
    </div>
  </div>

  
</aside>
        
      </div>
      <footer id="footer">
  
  <div class="outer">
    <div id="footer-info" class="inner">
      &copy; 2020 Jian Guo<br>
      Powered by <a href="http://hexo.io/" target="_blank">Hexo</a>
    </div>
  </div>
</footer>
    </div>
    <nav id="mobile-nav">
  
    <a href="/" class="mobile-nav-link">Home</a>
  
    <a href="/archives" class="mobile-nav-link">Archives</a>
  
</nav>
    

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>


  
<link rel="stylesheet" href="/fancybox/jquery.fancybox.css">

  
<script src="/fancybox/jquery.fancybox.pack.js"></script>




<script src="/js/script.js"></script>




  </div>
</body>
</html>